# Generated by Django 5.2.4 on 2025-07-29 17:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheating_detector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='SuspiciousEvent',
        ),
    ]
