# Generated by Django 5.2.4 on 2025-07-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheating_detector', '0002_alert_delete_suspiciousevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
